name = input('Ваше имя: ')
print('Приветствую ' + name)
a = int(input('Введите число А: '))
b = int(input('Введите число Б: '))
print('Теперь поменяем их местами))')
c = (a - b)
b = (b + c)
a = (b - c)
print('А равно: ' + str(a), ', а Б равно: ' + str(b))